import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { loginWithGithub } from '../api/api';
import { useRouter } from 'next/dist/client/router';

const Home: NextPage = () => {
  const router = useRouter();

  const login = async () => {
    const { data } = await loginWithGithub();
    console.log(data);
    router.push(data);
  };

  const goToEditor = () => {
    login();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
      <h1>CV-GENERATOR</h1>
      <button onClick={goToEditor}>Go To editor</button>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
