import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { loginWithGithub } from '../api/api';
import { useRouter } from 'next/dist/client/router';

const Home: NextPage = () => {
  const router = useRouter();

  const login = async () => {
    const { data } = await loginWithGithub();

    router.push(data);
  };

  const goToEditor = () => {
    login();
  };

  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.mainContent}>
          <h1>Resume generator</h1>
          <button onClick={goToEditor} className={styles.buttonFilled}>
            Go To editor <span style={{ marginLeft: 20 }}>&#8594;</span>
          </button>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
